name: Security Scans

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn clean install

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.9.6.0:spotbugs

      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml

      - name: Run OWASP Dependency-Check
        uses: dependency-check/DependencyCheck_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: information_security_lab1
          path: .
          format: "ALL"
          out: reports
          args: >
            --ossIndexUsername ${{ secrets.OSSINDEX_USER }}
            --ossIndexPassword ${{ secrets.OSSINDEX_TOKEN }}

      - name: Upload Dependency-Check reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: reports/dependency-check-report.*
